// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (migrate, studio, introspect) use the direct/session
    // connection — the transaction pooler in DATABASE_URL doesn't support
    // the advisory locks Prisma Migrate needs.
    url: process.env["DIRECT_URL"],
  },
});
